<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="54445" started-at="2018-10-14T21:34:14Z" finished-at="2018-10-14T21:35:08Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="54445" started-at="2018-10-14T21:34:14Z" finished-at="2018-10-14T21:35:08Z">
      <class name="com.was.qa.testcases.TransferFundsPageTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.was.qa.testcases.TransferFundsPageTest@68c4039c]" name="setUp" is-config="true" duration-ms="15178" started-at="2018-10-14T17:34:14Z" finished-at="2018-10-14T17:34:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="accountTransferToSameAccountTest()[pri:0, instance:com.was.qa.testcases.TransferFundsPageTest@68c4039c]" name="accountTransferToSameAccountTest" duration-ms="3901" started-at="2018-10-14T17:34:29Z" finished-at="2018-10-14T17:34:33Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.was.qa.testcases.TransferFundsPageTest.accountTransferToSameAccountTest(TransferFundsPageTest.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- accountTransferToSameAccountTest -->
        <test-method status="PASS" signature="cleanUp()[pri:0, instance:com.was.qa.testcases.TransferFundsPageTest@68c4039c]" name="cleanUp" is-config="true" duration-ms="807" started-at="2018-10-14T17:34:33Z" finished-at="2018-10-14T17:34:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanUp -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.was.qa.testcases.TransferFundsPageTest@68c4039c]" name="setUp" is-config="true" duration-ms="14941" started-at="2018-10-14T17:34:34Z" finished-at="2018-10-14T17:34:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="transferFundsPageTitleTest()[pri:0, instance:com.was.qa.testcases.TransferFundsPageTest@68c4039c]" name="transferFundsPageTitleTest" duration-ms="22" started-at="2018-10-14T17:34:49Z" finished-at="2018-10-14T17:34:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- transferFundsPageTitleTest -->
        <test-method status="PASS" signature="cleanUp()[pri:0, instance:com.was.qa.testcases.TransferFundsPageTest@68c4039c]" name="cleanUp" is-config="true" duration-ms="713" started-at="2018-10-14T17:34:49Z" finished-at="2018-10-14T17:34:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanUp -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.was.qa.testcases.TransferFundsPageTest@68c4039c]" name="setUp" is-config="true" duration-ms="14021" started-at="2018-10-14T17:34:49Z" finished-at="2018-10-14T17:35:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="insuffcientFundsTest()[pri:0, instance:com.was.qa.testcases.TransferFundsPageTest@68c4039c]" name="insuffcientFundsTest" duration-ms="4063" started-at="2018-10-14T17:35:03Z" finished-at="2018-10-14T17:35:08Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.was.qa.testcases.TransferFundsPageTest.insuffcientFundsTest(TransferFundsPageTest.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- insuffcientFundsTest -->
        <test-method status="PASS" signature="cleanUp()[pri:0, instance:com.was.qa.testcases.TransferFundsPageTest@68c4039c]" name="cleanUp" is-config="true" duration-ms="771" started-at="2018-10-14T17:35:08Z" finished-at="2018-10-14T17:35:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanUp -->
      </class> <!-- com.was.qa.testcases.TransferFundsPageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
